/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quad_lpv_cost_ext_cost_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[49] = {45, 1, 0, 45, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[44] = {40, 1, 0, 40, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};

/* quad_lpv_cost_ext_cost_fun:(i0[45],i1[4],i2[0],i3[40])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  a1=arg[3]? arg[3][6] : 0;
  a2=arg[3]? arg[3][0] : 0;
  a3=(a1*a2);
  a4=arg[3]? arg[3][7] : 0;
  a5=arg[3]? arg[3][1] : 0;
  a6=(a4*a5);
  a3=(a3+a6);
  a6=arg[3]? arg[3][8] : 0;
  a7=arg[3]? arg[3][2] : 0;
  a8=(a6*a7);
  a3=(a3+a8);
  a0=(a0-a3);
  a3=1000.;
  a8=(a3*a0);
  a0=(a0*a8);
  a8=arg[0]? arg[0][1] : 0;
  a9=arg[3]? arg[3][9] : 0;
  a10=(a9*a2);
  a11=arg[3]? arg[3][10] : 0;
  a12=(a11*a5);
  a10=(a10+a12);
  a12=arg[3]? arg[3][11] : 0;
  a13=(a12*a7);
  a10=(a10+a13);
  a8=(a8-a10);
  a10=(a3*a8);
  a8=(a8*a10);
  a0=(a0+a8);
  a8=arg[0]? arg[0][2] : 0;
  a10=arg[3]? arg[3][12] : 0;
  a13=(a10*a2);
  a14=arg[3]? arg[3][13] : 0;
  a15=(a14*a5);
  a13=(a13+a15);
  a15=arg[3]? arg[3][14] : 0;
  a16=(a15*a7);
  a13=(a13+a16);
  a8=(a8-a13);
  a3=(a3*a8);
  a8=(a8*a3);
  a0=(a0+a8);
  a8=arg[0]? arg[0][3] : 0;
  a3=arg[3]? arg[3][17] : 0;
  a13=(a3*a9);
  a16=arg[3]? arg[3][16] : 0;
  a17=(a16*a10);
  a13=(a13-a17);
  a17=(a13*a2);
  a18=(a3*a11);
  a19=(a16*a14);
  a18=(a18-a19);
  a19=(a18*a5);
  a17=(a17+a19);
  a19=(a3*a12);
  a20=(a16*a15);
  a19=(a19-a20);
  a20=(a19*a7);
  a17=(a17+a20);
  a8=(a8-a17);
  a17=500.;
  a20=(a17*a8);
  a8=(a8*a20);
  a0=(a0+a8);
  a8=arg[0]? arg[0][4] : 0;
  a20=arg[3]? arg[3][15] : 0;
  a21=(a20*a10);
  a22=(a3*a1);
  a21=(a21-a22);
  a22=(a21*a2);
  a23=(a20*a14);
  a24=(a3*a4);
  a23=(a23-a24);
  a24=(a23*a5);
  a22=(a22+a24);
  a24=(a20*a15);
  a25=(a3*a6);
  a24=(a24-a25);
  a25=(a24*a7);
  a22=(a22+a25);
  a8=(a8-a22);
  a22=(a17*a8);
  a8=(a8*a22);
  a0=(a0+a8);
  a8=arg[0]? arg[0][5] : 0;
  a22=(a16*a1);
  a25=(a20*a9);
  a22=(a22-a25);
  a2=(a22*a2);
  a25=(a16*a4);
  a26=(a20*a11);
  a25=(a25-a26);
  a5=(a25*a5);
  a2=(a2+a5);
  a5=(a16*a6);
  a26=(a20*a12);
  a5=(a5-a26);
  a7=(a5*a7);
  a2=(a2+a7);
  a8=(a8-a2);
  a2=(a17*a8);
  a8=(a8*a2);
  a0=(a0+a8);
  a8=arg[0]? arg[0][9] : 0;
  a2=arg[3]? arg[3][3] : 0;
  a7=(a1*a2);
  a26=arg[3]? arg[3][4] : 0;
  a27=(a4*a26);
  a7=(a7+a27);
  a27=arg[3]? arg[3][5] : 0;
  a28=(a6*a27);
  a7=(a7+a28);
  a8=(a8-a7);
  a7=(a17*a8);
  a8=(a8*a7);
  a0=(a0+a8);
  a8=arg[0]? arg[0][10] : 0;
  a7=(a9*a2);
  a28=(a11*a26);
  a7=(a7+a28);
  a28=(a12*a27);
  a7=(a7+a28);
  a8=(a8-a7);
  a7=(a17*a8);
  a8=(a8*a7);
  a0=(a0+a8);
  a8=arg[0]? arg[0][11] : 0;
  a7=(a10*a2);
  a28=(a14*a26);
  a7=(a7+a28);
  a28=(a15*a27);
  a7=(a7+a28);
  a8=(a8-a7);
  a7=(a17*a8);
  a8=(a8*a7);
  a0=(a0+a8);
  a8=arg[0]? arg[0][12] : 0;
  a13=(a13*a2);
  a18=(a18*a26);
  a13=(a13+a18);
  a19=(a19*a27);
  a13=(a13+a19);
  a8=(a8-a13);
  a13=(a17*a8);
  a8=(a8*a13);
  a0=(a0+a8);
  a8=arg[0]? arg[0][13] : 0;
  a21=(a21*a2);
  a23=(a23*a26);
  a21=(a21+a23);
  a24=(a24*a27);
  a21=(a21+a24);
  a8=(a8-a21);
  a21=(a17*a8);
  a8=(a8*a21);
  a0=(a0+a8);
  a8=arg[0]? arg[0][14] : 0;
  a22=(a22*a2);
  a25=(a25*a26);
  a22=(a22+a25);
  a5=(a5*a27);
  a22=(a22+a5);
  a8=(a8-a22);
  a22=(a17*a8);
  a8=(a8*a22);
  a0=(a0+a8);
  a8=arg[0]? arg[0][27] : 0;
  a8=(a8-a1);
  a22=(a17*a8);
  a8=(a8*a22);
  a0=(a0+a8);
  a8=arg[0]? arg[0][28] : 0;
  a8=(a8-a4);
  a22=(a17*a8);
  a8=(a8*a22);
  a0=(a0+a8);
  a8=arg[0]? arg[0][29] : 0;
  a8=(a8-a6);
  a22=(a17*a8);
  a8=(a8*a22);
  a0=(a0+a8);
  a8=arg[0]? arg[0][30] : 0;
  a8=(a8-a9);
  a22=(a17*a8);
  a8=(a8*a22);
  a0=(a0+a8);
  a8=arg[0]? arg[0][31] : 0;
  a8=(a8-a11);
  a22=(a17*a8);
  a8=(a8*a22);
  a0=(a0+a8);
  a8=arg[0]? arg[0][32] : 0;
  a8=(a8-a12);
  a22=(a17*a8);
  a8=(a8*a22);
  a0=(a0+a8);
  a8=arg[0]? arg[0][33] : 0;
  a8=(a8-a10);
  a22=(a17*a8);
  a8=(a8*a22);
  a0=(a0+a8);
  a8=arg[0]? arg[0][34] : 0;
  a8=(a8-a14);
  a22=(a17*a8);
  a8=(a8*a22);
  a0=(a0+a8);
  a8=arg[0]? arg[0][35] : 0;
  a8=(a8-a15);
  a17=(a17*a8);
  a8=(a8*a17);
  a0=(a0+a8);
  a8=arg[0]? arg[0][36] : 0;
  a17=(a9*a3);
  a22=(a10*a16);
  a17=(a17-a22);
  a8=(a8-a17);
  a17=200.;
  a22=(a17*a8);
  a8=(a8*a22);
  a0=(a0+a8);
  a8=arg[0]? arg[0][37] : 0;
  a22=(a11*a3);
  a5=(a14*a16);
  a22=(a22-a5);
  a8=(a8-a22);
  a22=(a17*a8);
  a8=(a8*a22);
  a0=(a0+a8);
  a8=arg[0]? arg[0][38] : 0;
  a22=(a12*a3);
  a5=(a15*a16);
  a22=(a22-a5);
  a8=(a8-a22);
  a22=(a17*a8);
  a8=(a8*a22);
  a0=(a0+a8);
  a8=arg[0]? arg[0][39] : 0;
  a10=(a10*a20);
  a22=(a1*a3);
  a10=(a10-a22);
  a8=(a8-a10);
  a10=(a17*a8);
  a8=(a8*a10);
  a0=(a0+a8);
  a8=arg[0]? arg[0][40] : 0;
  a14=(a14*a20);
  a10=(a4*a3);
  a14=(a14-a10);
  a8=(a8-a14);
  a14=(a17*a8);
  a8=(a8*a14);
  a0=(a0+a8);
  a8=arg[0]? arg[0][41] : 0;
  a15=(a15*a20);
  a3=(a6*a3);
  a15=(a15-a3);
  a8=(a8-a15);
  a15=(a17*a8);
  a8=(a8*a15);
  a0=(a0+a8);
  a8=arg[0]? arg[0][42] : 0;
  a1=(a1*a16);
  a9=(a9*a20);
  a1=(a1-a9);
  a8=(a8-a1);
  a1=(a17*a8);
  a8=(a8*a1);
  a0=(a0+a8);
  a8=arg[0]? arg[0][43] : 0;
  a4=(a4*a16);
  a11=(a11*a20);
  a4=(a4-a11);
  a8=(a8-a4);
  a4=(a17*a8);
  a8=(a8*a4);
  a0=(a0+a8);
  a8=arg[0]? arg[0][44] : 0;
  a6=(a6*a16);
  a12=(a12*a20);
  a6=(a6-a12);
  a8=(a8-a6);
  a17=(a17*a8);
  a8=(a8*a17);
  a0=(a0+a8);
  a8=arg[1]? arg[1][0] : 0;
  a17=arg[3]? arg[3][18] : 0;
  a8=(a8-a17);
  a17=1.0000000000000000e-03;
  a6=(a17*a8);
  a8=(a8*a6);
  a6=arg[1]? arg[1][1] : 0;
  a12=arg[3]? arg[3][19] : 0;
  a6=(a6-a12);
  a12=1.0000000000000000e-04;
  a12=(a12*a6);
  a6=(a6*a12);
  a8=(a8+a6);
  a6=arg[1]? arg[1][2] : 0;
  a12=arg[3]? arg[3][20] : 0;
  a6=(a6-a12);
  a12=(a17*a6);
  a6=(a6*a12);
  a8=(a8+a6);
  a6=arg[1]? arg[1][3] : 0;
  a12=arg[3]? arg[3][21] : 0;
  a6=(a6-a12);
  a17=(a17*a6);
  a6=(a6*a17);
  a8=(a8+a6);
  a0=(a0+a8);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_lpv_cost_ext_cost_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quad_lpv_cost_ext_cost_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_lpv_cost_ext_cost_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_lpv_cost_ext_cost_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quad_lpv_cost_ext_cost_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_lpv_cost_ext_cost_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quad_lpv_cost_ext_cost_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quad_lpv_cost_ext_cost_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quad_lpv_cost_ext_cost_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quad_lpv_cost_ext_cost_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quad_lpv_cost_ext_cost_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_lpv_cost_ext_cost_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_lpv_cost_ext_cost_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_lpv_cost_ext_cost_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_lpv_cost_ext_cost_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quad_lpv_cost_ext_cost_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_lpv_cost_ext_cost_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
