/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quad_lpv_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[49] = {45, 1, 0, 45, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[44] = {40, 1, 0, 40, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39};

/* quad_lpv_expl_ode_fun:(i0[45],i1[4],i2[40])->(o0[45]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][3] : 0;
  a1=arg[0]? arg[0][9] : 0;
  a0=(a0+a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][4] : 0;
  a1=arg[0]? arg[0][10] : 0;
  a0=(a0+a1);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][5] : 0;
  a1=arg[0]? arg[0][11] : 0;
  a0=(a0+a1);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[0]? arg[0][6] : 0;
  a1=arg[0]? arg[0][12] : 0;
  a0=(a0+a1);
  a2=3.1379615876461173e+02;
  a3=arg[2]? arg[2][31] : 0;
  a4=arg[2]? arg[2][22] : 0;
  a5=(a3*a4);
  a6=arg[2]? arg[2][32] : 0;
  a7=arg[2]? arg[2][23] : 0;
  a8=(a6*a7);
  a5=(a5+a8);
  a8=arg[2]? arg[2][33] : 0;
  a9=arg[2]? arg[2][24] : 0;
  a10=(a8*a9);
  a5=(a5+a10);
  a10=(a2*a5);
  a11=arg[1]? arg[1][3] : 0;
  a12=2.6294954679999998e-03;
  a13=arg[2]? arg[2][37] : 0;
  a14=(a12*a13);
  a15=arg[2]? arg[2][38] : 0;
  a14=(a14*a15);
  a16=2.3544056539999999e-03;
  a17=(a16*a15);
  a17=(a17*a13);
  a14=(a14-a17);
  a11=(a11-a14);
  a10=(a10*a11);
  a14=3.8030109280264412e+02;
  a17=arg[2]? arg[2][34] : 0;
  a18=(a17*a4);
  a19=arg[2]? arg[2][35] : 0;
  a20=(a19*a7);
  a18=(a18+a20);
  a20=arg[2]? arg[2][36] : 0;
  a21=(a20*a9);
  a18=(a18+a21);
  a21=(a14*a18);
  a22=arg[1]? arg[1][2] : 0;
  a23=arg[2]? arg[2][39] : 0;
  a16=(a16*a23);
  a16=(a16*a13);
  a24=3.1867821579999998e-03;
  a25=(a24*a13);
  a25=(a25*a23);
  a16=(a16-a25);
  a22=(a22-a16);
  a21=(a21*a22);
  a10=(a10-a21);
  a0=(a0+a10);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[0]? arg[0][7] : 0;
  a10=arg[0]? arg[0][13] : 0;
  a0=(a0+a10);
  a21=4.2473564328265076e+02;
  a16=(a21*a18);
  a25=arg[1]? arg[1][1] : 0;
  a24=(a24*a15);
  a24=(a24*a23);
  a12=(a12*a23);
  a12=(a12*a15);
  a24=(a24-a12);
  a25=(a25-a24);
  a16=(a16*a25);
  a24=arg[2]? arg[2][28] : 0;
  a4=(a24*a4);
  a12=arg[2]? arg[2][29] : 0;
  a7=(a12*a7);
  a4=(a4+a7);
  a7=arg[2]? arg[2][30] : 0;
  a9=(a7*a9);
  a4=(a4+a9);
  a9=(a2*a4);
  a9=(a9*a11);
  a16=(a16-a9);
  a0=(a0+a16);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[0]? arg[0][8] : 0;
  a16=arg[0]? arg[0][14] : 0;
  a0=(a0+a16);
  a9=(a14*a4);
  a9=(a9*a22);
  a26=(a21*a5);
  a26=(a26*a25);
  a9=(a9-a26);
  a0=(a0+a9);
  if (res[0]!=0) res[0][5]=a0;
  a0=(a23*a18);
  a9=(a15*a5);
  a26=(a0+a9);
  a26=(a21*a26);
  a26=(a26*a25);
  a27=(a15*a4);
  a28=(a13*a5);
  a29=(a27-a28);
  a30=(a14*a29);
  a27=(a14*a27);
  a30=(a30+a27);
  a30=(a30*a22);
  a26=(a26-a30);
  a30=(a13*a18);
  a27=(a23*a4);
  a31=(a30-a27);
  a32=(a2*a31);
  a27=(a2*a27);
  a32=(a32-a27);
  a32=(a32*a11);
  a26=(a26+a32);
  if (res[0]!=0) res[0][6]=a26;
  a29=(a21*a29);
  a28=(a21*a28);
  a29=(a29-a28);
  a29=(a29*a25);
  a4=(a13*a4);
  a0=(a0+a4);
  a0=(a14*a0);
  a0=(a0*a22);
  a29=(a29+a0);
  a5=(a23*a5);
  a18=(a15*a18);
  a0=(a5-a18);
  a28=(a2*a0);
  a5=(a2*a5);
  a28=(a28+a5);
  a28=(a28*a11);
  a29=(a29-a28);
  if (res[0]!=0) res[0][7]=a29;
  a0=(a14*a0);
  a18=(a14*a18);
  a0=(a0-a18);
  a0=(a0*a22);
  a31=(a21*a31);
  a30=(a21*a30);
  a31=(a31+a30);
  a31=(a31*a25);
  a0=(a0-a31);
  a9=(a9+a4);
  a9=(a2*a9);
  a9=(a9*a11);
  a0=(a0+a9);
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[0]? arg[0][18] : 0;
  a1=(a1+a0);
  if (res[0]!=0) res[0][9]=a1;
  a1=arg[0]? arg[0][19] : 0;
  a10=(a10+a1);
  if (res[0]!=0) res[0][10]=a10;
  a10=arg[0]? arg[0][20] : 0;
  a16=(a16+a10);
  a10=1.1061946902654867e+00;
  a1=arg[1]? arg[1][0] : 0;
  a10=(a10*a1);
  a16=(a16+a10);
  if (res[0]!=0) res[0][11]=a16;
  a16=arg[0]? arg[0][15] : 0;
  a10=arg[0]? arg[0][21] : 0;
  a16=(a16+a10);
  a0=arg[2]? arg[2][25] : 0;
  a9=(a3*a0);
  a4=arg[2]? arg[2][26] : 0;
  a31=(a6*a4);
  a9=(a9+a31);
  a31=arg[2]? arg[2][27] : 0;
  a30=(a8*a31);
  a9=(a9+a30);
  a30=(a2*a9);
  a30=(a30*a11);
  a18=9.0400000000000003e-01;
  a29=(a15/a18);
  a29=(a29*a1);
  a28=(a17*a0);
  a5=(a19*a4);
  a28=(a28+a5);
  a5=(a20*a31);
  a28=(a28+a5);
  a5=(a14*a28);
  a5=(a5*a22);
  a29=(a29+a5);
  a30=(a30-a29);
  a16=(a16+a30);
  if (res[0]!=0) res[0][12]=a16;
  a16=arg[0]? arg[0][16] : 0;
  a30=arg[0]? arg[0][22] : 0;
  a16=(a16+a30);
  a29=(a13/a18);
  a29=(a29*a1);
  a5=(a21*a28);
  a5=(a5*a25);
  a29=(a29+a5);
  a0=(a24*a0);
  a4=(a12*a4);
  a0=(a0+a4);
  a31=(a7*a31);
  a0=(a0+a31);
  a31=(a2*a0);
  a31=(a31*a11);
  a29=(a29-a31);
  a16=(a16+a29);
  if (res[0]!=0) res[0][13]=a16;
  a16=arg[0]? arg[0][17] : 0;
  a29=arg[0]? arg[0][23] : 0;
  a16=(a16+a29);
  a31=(a14*a0);
  a31=(a31*a22);
  a4=(a21*a9);
  a4=(a4*a25);
  a31=(a31-a4);
  a16=(a16+a31);
  if (res[0]!=0) res[0][14]=a16;
  a16=(a23*a13);
  a16=(a16/a18);
  a16=(a16*a1);
  a31=(a23*a28);
  a4=(a15*a9);
  a5=(a31+a4);
  a5=(a21*a5);
  a5=(a5*a25);
  a16=(a16+a5);
  a5=(a15*a0);
  a26=(a13*a9);
  a32=(a5-a26);
  a27=(a14*a32);
  a5=(a14*a5);
  a27=(a27+a5);
  a27=(a27*a22);
  a16=(a16-a27);
  a27=(a13*a28);
  a5=(a23*a0);
  a33=(a27-a5);
  a34=(a2*a33);
  a5=(a2*a5);
  a34=(a34-a5);
  a34=(a34*a11);
  a16=(a16+a34);
  if (res[0]!=0) res[0][15]=a16;
  a16=(a23*a15);
  a16=(a16/a18);
  a16=(a16*a1);
  a32=(a21*a32);
  a26=(a21*a26);
  a32=(a32-a26);
  a32=(a32*a25);
  a16=(a16+a32);
  a0=(a13*a0);
  a31=(a31+a0);
  a31=(a14*a31);
  a31=(a31*a22);
  a16=(a16+a31);
  a9=(a23*a9);
  a28=(a15*a28);
  a31=(a9-a28);
  a32=(a2*a31);
  a9=(a2*a9);
  a32=(a32+a9);
  a32=(a32*a11);
  a16=(a16-a32);
  if (res[0]!=0) res[0][16]=a16;
  a31=(a14*a31);
  a28=(a14*a28);
  a31=(a31-a28);
  a31=(a31*a22);
  a28=casadi_sq(a15);
  a16=casadi_sq(a13);
  a28=(a28+a16);
  a28=(a28/a18);
  a28=(a28*a1);
  a33=(a21*a33);
  a27=(a21*a27);
  a33=(a33+a27);
  a33=(a33*a25);
  a28=(a28+a33);
  a31=(a31-a28);
  a4=(a4+a0);
  a4=(a2*a4);
  a4=(a4*a11);
  a31=(a31+a4);
  if (res[0]!=0) res[0][17]=a31;
  if (res[0]!=0) res[0][18]=a10;
  if (res[0]!=0) res[0][19]=a30;
  if (res[0]!=0) res[0][20]=a29;
  a29=arg[0]? arg[0][24] : 0;
  a30=9.8100000000000005e+00;
  a10=(a30*a20);
  a31=(a14*a10);
  a31=(a31*a22);
  a4=(a30*a8);
  a0=(a2*a4);
  a0=(a0*a11);
  a31=(a31-a0);
  a29=(a29+a31);
  if (res[0]!=0) res[0][21]=a29;
  a29=arg[0]? arg[0][25] : 0;
  a30=(a30*a7);
  a31=(a2*a30);
  a31=(a31*a11);
  a0=(a21*a10);
  a0=(a0*a25);
  a31=(a31-a0);
  a29=(a29+a31);
  if (res[0]!=0) res[0][22]=a29;
  a29=arg[0]? arg[0][26] : 0;
  a31=(a21*a4);
  a31=(a31*a25);
  a0=(a14*a30);
  a0=(a0*a22);
  a31=(a31-a0);
  a29=(a29+a31);
  if (res[0]!=0) res[0][23]=a29;
  a29=(a15*a30);
  a31=(a14*a29);
  a0=(a13*a4);
  a29=(a0-a29);
  a28=(a14*a29);
  a31=(a31-a28);
  a31=(a31*a22);
  a28=(a23*a10);
  a33=(a15*a4);
  a27=(a28+a33);
  a27=(a21*a27);
  a27=(a27*a25);
  a31=(a31-a27);
  a27=(a23*a30);
  a1=(a13*a10);
  a18=(a27-a1);
  a16=(a2*a18);
  a27=(a2*a27);
  a16=(a16+a27);
  a16=(a16*a11);
  a31=(a31+a16);
  if (res[0]!=0) res[0][24]=a31;
  a29=(a21*a29);
  a0=(a21*a0);
  a29=(a29+a0);
  a29=(a29*a25);
  a13=(a13*a30);
  a28=(a28+a13);
  a28=(a14*a28);
  a28=(a28*a22);
  a29=(a29-a28);
  a23=(a23*a4);
  a4=(a2*a23);
  a15=(a15*a10);
  a23=(a15-a23);
  a10=(a2*a23);
  a4=(a4-a10);
  a4=(a4*a11);
  a29=(a29+a4);
  if (res[0]!=0) res[0][25]=a29;
  a1=(a21*a1);
  a18=(a21*a18);
  a1=(a1-a18);
  a1=(a1*a25);
  a23=(a14*a23);
  a15=(a14*a15);
  a23=(a23+a15);
  a23=(a23*a22);
  a1=(a1+a23);
  a33=(a33+a13);
  a33=(a2*a33);
  a33=(a33*a11);
  a1=(a1-a33);
  if (res[0]!=0) res[0][26]=a1;
  a1=arg[0]? arg[0][36] : 0;
  if (res[0]!=0) res[0][27]=a1;
  a1=arg[0]? arg[0][37] : 0;
  if (res[0]!=0) res[0][28]=a1;
  a1=arg[0]? arg[0][38] : 0;
  if (res[0]!=0) res[0][29]=a1;
  a1=arg[0]? arg[0][39] : 0;
  if (res[0]!=0) res[0][30]=a1;
  a1=arg[0]? arg[0][40] : 0;
  if (res[0]!=0) res[0][31]=a1;
  a1=arg[0]? arg[0][41] : 0;
  if (res[0]!=0) res[0][32]=a1;
  a1=arg[0]? arg[0][42] : 0;
  if (res[0]!=0) res[0][33]=a1;
  a1=arg[0]? arg[0][43] : 0;
  if (res[0]!=0) res[0][34]=a1;
  a1=arg[0]? arg[0][44] : 0;
  if (res[0]!=0) res[0][35]=a1;
  a1=-3.8030109280264412e+02;
  a33=(a1*a17);
  a33=(a33*a22);
  a13=(a2*a3);
  a13=(a13*a11);
  a33=(a33+a13);
  if (res[0]!=0) res[0][36]=a33;
  a33=(a1*a19);
  a33=(a33*a22);
  a13=(a2*a6);
  a13=(a13*a11);
  a33=(a33+a13);
  if (res[0]!=0) res[0][37]=a33;
  a1=(a1*a20);
  a1=(a1*a22);
  a2=(a2*a8);
  a2=(a2*a11);
  a1=(a1+a2);
  if (res[0]!=0) res[0][38]=a1;
  a17=(a21*a17);
  a17=(a17*a25);
  a1=-3.1379615876461173e+02;
  a2=(a1*a24);
  a2=(a2*a11);
  a17=(a17+a2);
  if (res[0]!=0) res[0][39]=a17;
  a19=(a21*a19);
  a19=(a19*a25);
  a17=(a1*a12);
  a17=(a17*a11);
  a19=(a19+a17);
  if (res[0]!=0) res[0][40]=a19;
  a21=(a21*a20);
  a21=(a21*a25);
  a1=(a1*a7);
  a1=(a1*a11);
  a21=(a21+a1);
  if (res[0]!=0) res[0][41]=a21;
  a21=-4.2473564328265076e+02;
  a3=(a21*a3);
  a3=(a3*a25);
  a24=(a14*a24);
  a24=(a24*a22);
  a3=(a3+a24);
  if (res[0]!=0) res[0][42]=a3;
  a6=(a21*a6);
  a6=(a6*a25);
  a12=(a14*a12);
  a12=(a12*a22);
  a6=(a6+a12);
  if (res[0]!=0) res[0][43]=a6;
  a21=(a21*a8);
  a21=(a21*a25);
  a14=(a14*a7);
  a14=(a14*a22);
  a21=(a21+a14);
  if (res[0]!=0) res[0][44]=a21;
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_lpv_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quad_lpv_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_lpv_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_lpv_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quad_lpv_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_lpv_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quad_lpv_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quad_lpv_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quad_lpv_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int quad_lpv_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quad_lpv_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_lpv_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_lpv_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_lpv_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_lpv_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quad_lpv_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_lpv_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
